version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - .env
    container_name: bot
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    networks:
      - db-bot_net
  db:
    image: 'postgres:15'
    container_name: db
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-bot_net
networks:
  db-bot_net:
    driver: bridge
volumes:
  db-data: